version: '3.7'
services:
  db:
    build: ./db
    container_name: db_mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
  app:
    #container_name: python_app
    build: ./app
    restart: always
    links:
      - db
    #expose:
    #  - '5000'
    #  - '6379'
    #ports:
    #  - '5000:5000'
    #  - '6379:6379'
    deploy:
      replicas: 3
  lb:
    container_name: lb
    build: ./lb
    restart: always
    links:
      - app
    expose:
      - '80'
    ports:
      - '8080:80'


